In [4]:
from sklearn.impute import KNNImputer
import numpy as np
import pandas as pd

In [5]:

X = [ [3, np.NaN, 5], [1, 0, 0], [3, 3, 3] ]
print("X: ", X)
print("===========")

X:  [[3, nan, 5], [1, 0, 0], [3, 3, 3]]


In [7]:
x = pd.DataFrame(X)

In [8]:
x

0    1  2
0  3  NaN  5
1  1  0.0  0
2  3  3.0  3

In [9]:
imputer = KNNImputer(n_neighbors= 1)
impute_with_1 = imputer.fit_transform(x)

print("\nImpute with 1 Neighbour: \n", impute_with_1)



imputer = KNNImputer(n_neighbors= 2)
impute_with_2 = imputer.fit_transform(X)

print("\n Impute with 2 Neighbours: \n", impute_with_1)



Impute with 1 Neighbour: 
 [[3. 3. 5.]
 [1. 0. 0.]
 [3. 3. 3.]]

 Impute with 2 Neighbours: 
 [[3. 3. 5.]
 [1. 0. 0.]
 [3. 3. 3.]]
